#!/usr/bin/env node
/**
 * One-time URL curation script for PG Patrol replacement images.
 *
 * Uses the Pexels API to build a list of ~150 pleasant stock photo CDN URLs
 * organized by aspect ratio bucket (landscape, portrait, square).
 *
 * Usage:
 *   PEXELS_API_KEY=your_key node scripts/curate-images.mjs
 *   PEXELS_API_KEY=your_key node scripts/curate-images.mjs --preview   # also downloads thumbnails
 *
 * The API key is read from an environment variable and never written to any file.
 * Output: src/data/replacement-image-urls.ts
 */

import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const OUTPUT_PATH = join(ROOT, 'src/data/replacement-image-urls.ts');
const PREVIEW_DIR = join(__dirname, 'preview');

const PEXELS_API_KEY = process.env.PEXELS_API_KEY;
if (!PEXELS_API_KEY) {
  console.error('Error: PEXELS_API_KEY environment variable is required.');
  console.error('Get a free API key at https://www.pexels.com/api/');
  console.error('Usage: PEXELS_API_KEY=your_key node scripts/curate-images.mjs');
  process.exit(1);
}

const QUERIES = [
  'nature landscape',
  'flowers garden',
  'blue sky clouds',
  'ocean waves',
  'mountains hiking',
  'food cooking',
  'architecture building',
  'abstract colorful',
  'animals wildlife',
  'forest trees',
];

const TARGET_PER_BUCKET = 50;
const PEXELS_BASE = 'https://api.pexels.com/v1/search';

/** Classify image into aspect ratio bucket */
function classifyBucket(width, height) {
  const ratio = width / height;
  if (ratio >= 1.3) return 'landscape';
  if (ratio <= 0.77) return 'portrait';
  return 'square';
}

/** Build a sized CDN URL (no API key embedded) */
function buildCdnUrl(photo, targetWidth = 400) {
  // Pexels CDN URLs are publicly accessible
  return `${photo.src.original}?auto=compress&cs=tinysrgb&w=${targetWidth}`;
}

async function searchPexels(query, page = 1, perPage = 40) {
  const url = `${PEXELS_BASE}?query=${encodeURIComponent(query)}&per_page=${perPage}&page=${page}`;
  const res = await fetch(url, {
    headers: { Authorization: PEXELS_API_KEY },
  });
  if (!res.ok) {
    throw new Error(`Pexels API error: ${res.status} ${res.statusText}`);
  }
  return res.json();
}

async function downloadPreview(url, filename) {
  const res = await fetch(url);
  if (!res.ok) return;
  const buffer = Buffer.from(await res.arrayBuffer());
  writeFileSync(join(PREVIEW_DIR, filename), buffer);
}

async function main() {
  const downloadPreviews = process.argv.includes('--preview');

  const buckets = { landscape: [], portrait: [], square: [] };
  const seenIds = new Set();

  console.log('Searching Pexels for pleasant stock photos...\n');

  for (const query of QUERIES) {
    for (let page = 1; page <= 3; page++) {
      // Check if all buckets are full
      if (
        buckets.landscape.length >= TARGET_PER_BUCKET &&
        buckets.portrait.length >= TARGET_PER_BUCKET &&
        buckets.square.length >= TARGET_PER_BUCKET
      ) {
        break;
      }

      try {
        const data = await searchPexels(query, page);
        for (const photo of data.photos) {
          if (seenIds.has(photo.id)) continue;
          seenIds.add(photo.id);

          const bucket = classifyBucket(photo.width, photo.height);
          if (buckets[bucket].length >= TARGET_PER_BUCKET) continue;

          buckets[bucket].push(buildCdnUrl(photo));
          console.log(`  [${bucket}] ${photo.id}: ${photo.alt || query} (${photo.width}x${photo.height})`);

          if (downloadPreviews) {
            if (!existsSync(PREVIEW_DIR)) mkdirSync(PREVIEW_DIR, { recursive: true });
            await downloadPreview(photo.src.tiny, `${bucket}_${photo.id}.jpg`);
          }
        }
      } catch (err) {
        console.warn(`  Warning: Failed to search "${query}" page ${page}: ${err.message}`);
      }

      // Rate limit: ~1 request per second
      await new Promise((r) => setTimeout(r, 1000));
    }
  }

  console.log(`\nCollected: landscape=${buckets.landscape.length}, portrait=${buckets.portrait.length}, square=${buckets.square.length}`);

  // Generate TypeScript output
  const formatUrls = (urls) =>
    urls.map((u) => `    '${u}',`).join('\n');

  const output = `/**
 * Curated CDN URLs for NSFW image replacements.
 * Generated by scripts/curate-images.mjs — do not edit manually.
 *
 * These are direct CDN URLs from Pexels (free license, no attribution required).
 * No API keys are embedded — the URLs are publicly accessible.
 */

import type { AspectBucket } from '../assets/replacements/manifest';

export const REPLACEMENT_URLS: Record<AspectBucket, string[]> = {
  landscape: [
${formatUrls(buckets.landscape)}
  ],
  portrait: [
${formatUrls(buckets.portrait)}
  ],
  square: [
${formatUrls(buckets.square)}
  ],
};
`;

  writeFileSync(OUTPUT_PATH, output, 'utf-8');
  console.log(`\nWrote ${OUTPUT_PATH}`);

  if (downloadPreviews) {
    console.log(`Previews saved to ${PREVIEW_DIR}/`);
  }
}

main().catch((err) => {
  console.error('Fatal error:', err);
  process.exit(1);
});
